### ISSUE TITLE
csssimple 与 precss 一块使用就会出现 string.replace is not function

### ISSUE THREAD

**Issue by hidumou** [sivan/postcss-csssimple#1]
路人甲...

**Comment by sivan** [comment]
@haner199401 可否把你的配置（gulp 或者什么）发出来看一下？

**Comment by haner199401** [comment]
![image](https://cloud.githubusercontent.com/assets/8998933/11737952/51458a20-a019-11e5-9970-937a01ebbe6b.png)

**Comment by hidumou** [comment]
![image](https://cloud.githubusercontent.com/assets/8998933/11737990/9a88a712-a019-11e5-9ca6-87eb4cd43683.png)

**Comment by hidumou** [comment]
刚开始学习 postcss.. 不知道你又遇到吗？

**Comment by hidumou** [comment]
![image](https://cloud.githubusercontent.com/assets/8998933/11738307/940cb254-a01c-11e5-95b1-a5d948e8093f.png)

display:inline-block; 时候就出现了

**Comment by sivan** [comment]
@haner199401 
尝试一下变换 postcss 里组件的调用顺序能否解决？让 `precss` 永远排在最前面。

``` javascript
gulp.task('postcss', function() {
    var processors = [
        precss,
        {{other plugins}},
        csssimple
    ];
    return gulp.src(compile.src.css)
        .pipe(postcss(processors))
        ...
});
```

**Comment by hidumou** [comment]
不行的，但我注释fixInineBlock 就可以。。。。

**Comment by sivan** [comment]
@haner199401 测了一下确实跟 precss 共存时会存在兼容问题。我用 postcss-scss 作 parser 测试是可用的，不晓得 precss 做了什么处理导致 PostCSS 的 API 取不到应有的数据。有时间我再研究一下。
如果你要应用在项目里，可以暂时把 CSSSimple 关了。也可以尝试使用 Sass + PostCSS 的方式取代 precss 的功能。

**Comment by hidumou** [comment]
已采用，THX
